### ISSUE TITLE
Error Occurred while generating schema 

### ISSUE THREAD

**Issue by ashutosh426** [jsonsystems/public#25]
{
    "headers": {
        "normalizedNames": {},
        "lazyUpdate": null,
        "headers": {}
    },
    "status": 0,
    "statusText": "Unknown Error",
    "url": "https://api.jsonschema.net/v1/graphs:deduceSchema",
    "ok": false,
    "name": "HttpErrorResponse",
    "message": "Http failure response for https://api.jsonschema.net/v1/graphs:deduceSchema: 0 Unknown Error",
    "error": {
        "isTrusted": true
    }
}

**Comment by jackwootton** [comment]
Hi,

Is this still occurring? Can you provide the JSON you're using?

**Comment by jackwootton** [comment]
Closing due inactivity.
