### ISSUE TITLE
Error Occurred while generating schema

### ISSUE THREAD

**Issue by BerLP2021** [jsonsystems/public#28]
{
    "headers": {
        "normalizedNames": {},
        "lazyUpdate": null,
        "headers": {}
    },
    "status": 0,
    "statusText": "Unknown Error",
    "url": "https://api.jsonschema.net/v1:deduceGraph",
    "ok": false,
    "name": "HttpErrorResponse",
    "message": "Http failure response for https://api.jsonschema.net/v1:deduceGraph: 0 Unknown Error",
    "error": {
        "isTrusted": true
    }
}

**Comment by jackwootton** [comment]
Hi, thanks for reporting the issue. Can you provide the JSON (and settings) you used? If you don't want to post the JSON here, feel free to email help@jsonschema.net.

**Comment by DukePaulOz** [comment]
Hi, I'm getting exactly the same error. Any info on how to fix this?

**Comment by jackwootton** [comment]
Can you provide the JSON you're submitting and the settings you're using so I can recreate the issue.
