### ISSUE TITLE
Error, cant submit to see the schema

### ISSUE THREAD

**Issue by Mar-Spitt** [jsonsystems/public#6]
When I tried to submit the example I had the following error, the same thing happen when I tried with another json code
```json
{
    "headers": {
        "normalizedNames": {},
        "lazyUpdate": null,
        "headers": {}
    },
    "status": 0,
    "statusText": "Unknown Error",
    "url": "https://api.jsonschema.net/v1/graphs:deduceSchema",
    "ok": false,
    "name": "HttpErrorResponse",
    "message": "Http failure response for https://api.jsonschema.net/v1/graphs:deduceSchema: 0 Unknown Error",
    "error": {
        "isTrusted": true
    }
}
```

![101](https://user-images.githubusercontent.com/80590653/165114127-927c7029-2cd6-4a9b-ac01-349cf07799c8.PNG)

**Comment by jackwootton** [comment]
@Mar-Spitt Thanks for reporting the issue. Do you see the same thing if you go to the manage schema view (https://jsonschema.net/app/schemas)?

**Comment by Mar-Spitt** [comment]
Yes, is the same error :(
![102](https://user-images.githubusercontent.com/80590653/165152083-309cef35-1015-4faf-bb8c-9f311c4bed62.PNG)

**Comment by jackwootton** [comment]
Sorry about that. Can you share any information from developer tools (developer console)? Perhaps the network information and/or anything from the console?

**Comment by jackwootton** [comment]
[Mar-Spitt](https://github.com/Mar-Spitt) - let me know if there's anything I can help with here :)
